### ISSUE TITLE
EXT: error boundary messages for end users

### ISSUE THREAD

**Issue by wchrapka** [kyma-project/busola#1421] opened 2022-06-09 17:47 UTC
**Description**

When EXT config bugs busola, user should receive information via the app itself. Include error messages in the error boundaries and add custom messages for the (catched) errors that appear as the result of misconfiguration.

**Comment by Wawrzyn321** [comment] 2022-06-10 06:59
Duplicate of #1412

**Closed** 2023-01-04 13:07 UTC
Labels: kind/feature
