### ISSUE TITLE
Extensibility nodes are not checked for required permissions

### ISSUE THREAD

**Issue by Wawrzyn321** [kyma-project/busola#2193] opened 2022-12-19 09:55 UTC
**Description**

**Expected result**

If user has no access to e.g. Functions, Functions EXT node should not be displayed in left nav.

**Steps to reproduce**

Just make `permissionSetSelector` return `[]`, simulating no permissions at all.

**Comment by valentinvieriu** [comment] 2022-12-20 11:52
duplicate of https://github.com/kyma-project/busola/issues/2212

**Closed by valentinvieriu** 2022-12-20 11:52 UTC
Labels: kind/bug
