### ISSUE TITLE
Combo boxes on edit view do not work on Safari

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#2670] opened 2023-12-01 05:41 UTC
**Description**

**Expected result**

Combo boxes should open

**Actual result**

Combo boxes are closed automatically

**Steps to reproduce**

Use latest Safari on Mac. And try to create or edit a resource

**Troubleshooting**

https://github.com/kyma-project/busola/assets/478866/b4033429-d80e-4ecf-b2fb-c07454c314c5

**Comment by mrCherry97** [comment] 2023-12-07 10:35
Potentially it will be fixed with https://github.com/kyma-project/busola/issues/2661

**Comment by mrCherry97** [comment] 2024-11-07 08:15
Can't reproduce.

**Closed by mrCherry97** 2024-11-07 08:15 UTC
Labels: kind/bug
