### ISSUE TITLE
UXC-10 & 15: Cannot use semantic color for warning and say “error”. It should be either orange - warning or red - error

### ISSUE THREAD

**Issue by mrCherry97** [kyma-project/busola#3001] opened 2024-06-25 09:45 UTC
**Description**
UXC-10 & 15: Cannot use semantic color for warning and say “error”. It should be either orange - warning or red - error.
We should adjust `highlights` in extensions.
- [x] severless https://github.com/kyma-project/serverless/pull/1032
- [x] telemetry-menager https://github.com/kyma-project/telemetry-manager/pull/1211

**Actual result**
<img width="1160" alt="image" src="https://github.com/kyma-project/busola/assets/46759954/60977bc1-d6e7-4fc4-9807-df37eb8bd605">

**Comment by vicslavova** [comment] 2024-09-16 11:58
- Processing/intermediate statuses shouldn't be red, make them grey (and remove the error icon)
- Popover shouldn't be automatically closing once I've clicked on it
- Could the text in the popover be more readable?
- We couldn't reproduce an actual error to see if errors are now red
- In the screenshots we again see different status wording, is this on purpose? Here I have two functions I created and one of them said "Pending" and the other one said "Building"

<img width="2021" alt="image" src="https://github.com/user-attachments/assets/4b4c534f-1fbc-4a3d-bc04-f26597dcf3c8">
<img width="1157" alt="image" src="https://github.com/user-attachments/assets/86ba2205-a753-4051-9d1c-3b995edce8e9">

**Comment by mrCherry97** [comment] 2024-09-17 07:19
hi @vicslavova 
1. https://github.com/kyma-project/serverless/pull/1184 - fix for badges color
2. Popover shouldn't be automatically closing once I've clicked on it - I can't reproduce that, please refresh the page and double-check
3. Could the text in the popover be more readable? - https://github.com/kyma-project/serverless/issues/1185
4. We couldn't reproduce an actual error to see if errors are now red - I checked, and they are red
5. They are two different states, if you need more details, you can ask @kwiatekus he is the PO of the team that is developing functions

**Closed** 2024-09-17 07:19 UTC
Labels: kind/bug
